# TCL File Generated by Component Editor 17.0
# Fri Nov 17 13:37:46 CET 2017
# DO NOT MODIFY


# 
# eln "eln" v1.0
# Taupiac R. 2017.11.17.13:37:46
# transmitter for digital link
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module eln
# 
set_module_property DESCRIPTION "transmitter for digital link"
set_module_property NAME eln
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP CSP
set_module_property AUTHOR "Taupiac R."
set_module_property DISPLAY_NAME eln
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL eln
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file eln.vhd VHDL PATH eln.vhd
add_fileset_file FIFO_nMots_mBits.vhd VHDL PATH FIFO_nMots_mBits.vhd
add_fileset_file SerialData.vhd VHDL PATH SerialData.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_eln
# 
add_interface avalon_eln avalon end
set_interface_property avalon_eln addressUnits WORDS
set_interface_property avalon_eln associatedClock clock
set_interface_property avalon_eln associatedReset reset_n
set_interface_property avalon_eln bitsPerSymbol 8
set_interface_property avalon_eln burstOnBurstBoundariesOnly false
set_interface_property avalon_eln burstcountUnits WORDS
set_interface_property avalon_eln explicitAddressSpan 0
set_interface_property avalon_eln holdTime 0
set_interface_property avalon_eln linewrapBursts false
set_interface_property avalon_eln maximumPendingReadTransactions 0
set_interface_property avalon_eln maximumPendingWriteTransactions 0
set_interface_property avalon_eln readLatency 0
set_interface_property avalon_eln readWaitStates 0
set_interface_property avalon_eln readWaitTime 0
set_interface_property avalon_eln setupTime 0
set_interface_property avalon_eln timingUnits Cycles
set_interface_property avalon_eln writeWaitTime 0
set_interface_property avalon_eln ENABLED true
set_interface_property avalon_eln EXPORT_OF ""
set_interface_property avalon_eln PORT_NAME_MAP ""
set_interface_property avalon_eln CMSIS_SVD_VARIABLES ""
set_interface_property avalon_eln SVD_ADDRESS_GROUP ""

add_interface_port avalon_eln rd read Input 1
add_interface_port avalon_eln wr write Input 1
add_interface_port avalon_eln D_in writedata Input 8
add_interface_port avalon_eln D_out readdata Output 8
add_interface_port avalon_eln Addr address Input 2
set_interface_assignment avalon_eln embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_eln embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_eln embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_eln embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock Clk clk Input 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock ""
set_interface_property reset_n synchronousEdges NONE
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n reset_n reset_n Input 1


# 
# connection point Irq_ELN_n
# 
add_interface Irq_ELN_n interrupt end
set_interface_property Irq_ELN_n associatedAddressablePoint avalon_eln
set_interface_property Irq_ELN_n associatedClock clock
set_interface_property Irq_ELN_n associatedReset reset_n
set_interface_property Irq_ELN_n bridgedReceiverOffset ""
set_interface_property Irq_ELN_n bridgesToReceiver ""
set_interface_property Irq_ELN_n ENABLED true
set_interface_property Irq_ELN_n EXPORT_OF ""
set_interface_property Irq_ELN_n PORT_NAME_MAP ""
set_interface_property Irq_ELN_n CMSIS_SVD_VARIABLES ""
set_interface_property Irq_ELN_n SVD_ADDRESS_GROUP ""

add_interface_port Irq_ELN_n IRQ_ELN_n irq_n Output 1


# 
# connection point Line
# 
add_interface Line conduit end
set_interface_property Line associatedClock clock
set_interface_property Line associatedReset reset_n
set_interface_property Line ENABLED true
set_interface_property Line EXPORT_OF ""
set_interface_property Line PORT_NAME_MAP ""
set_interface_property Line CMSIS_SVD_VARIABLES ""
set_interface_property Line SVD_ADDRESS_GROUP ""

add_interface_port Line Line_ELN export Output 1

